# -*- coding: utf-8 -*-
"""college_transport_tracker.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1O_lpBD7k4yAGePr0SnNnSAZc8TZERlLO
"""

# bus_tracker.py - College Transport Management System

buses = [
    {
        "number": "B01",
        "route": "Bhopal Route A",
        "start": "MP Nagar",
        "destination": "VIT Bhopal",
        "stops": ["MP Nagar", "Board Office", "BHEL", "Sehore Road", "VIT Bhopal"],
        "time": "7:30 AM",
        "capacity": 20,
        "seats": 20,
        "status": "On Time",
    },
    {
        "number": "B02",
        "route": "Bhopal Route B",
        "start": "Kolar Road",
        "destination": "VIT Bhopal",
        "stops": ["Kolar Road", "Nehru Nagar", "Misrod", "Sehore Road", "VIT Bhopal"],
        "time": "7:45 AM",
        "capacity": 15,
        "seats": 15,
        "status": "Delayed",
    },
    {
        "number": "B03",
        "route": "Bhopal Route C",
        "start": "Bairagarh",
        "destination": "VIT Bhopal",
        "stops": ["Bairagarh", "Lalghati", "Bhopal Talkies", "Sehore Road", "VIT Bhopal"],
        "time": "8:00 AM",
        "capacity": 10,
        "seats": 10,
        "status": "On Time",
    },
]

# Track student bookings in memory
bookings = []


def get_bus(bus_num):
    """Helper to fetch bus dict by bus number."""
    bus_num = bus_num.upper()
    for bus in buses:
        if bus["number"] == bus_num:
            return bus
    return None


def search_bus():
    print("\n--- SEARCH BUS ---")
    query = input("Enter bus number or starting location: ").lower()
    if query == "":
        print("Search term cannot be empty.")
        return

    found = False
    for bus in buses:
        if query in bus["number"].lower() or query in bus["start"].lower():
            print(f"\nBus #:       {bus['number']}")
            print(f"Route:       {bus['route']}")
            print(f"Starts From: {bus['start']}")
            print(f"Destination: {bus['destination']}")
            print(f"Departure:   {bus['time']}")
            print(f"Seats Left:  {bus['seats']}")
            print(f"Status:      {bus['status']}")
            found = True

    if not found:
        print("No matching buses found.")


def view_route():
    print("\n--- VIEW ROUTE ---")
    bus_num = input("Enter bus number: ")
    bus = get_bus(bus_num)

    if not bus:
        print(f"Bus '{bus_num}' not found.")
        return

    print(f"\nRoute for {bus['number']} ({bus['route']}):")
    for idx, stop in enumerate(bus["stops"], start=1):
        print(f"  {idx}. {stop}")


def check_seats():
    print("\n--- SEAT AVAILABILITY ---")
    bus_num = input("Enter bus number: ")
    bus = get_bus(bus_num)

    if not bus:
        print("Bus not found.")
        return

    print(f"Bus {bus['number']} | Available: {bus['seats']} / Total: {bus['capacity']}")


def book_seat(student_name, student_id):
    print("\n--- BOOK A SEAT ---")
    bus_num = input("Enter bus number: ").upper()
    bus = get_bus(bus_num)

    if not bus:
        print("Bus not found.")
        return

    # Check if student already booked this bus
    for b in bookings:
        if b["student_id"] == student_id and b["bus_number"] == bus_num:
            print("You already have a booking on this bus.")
            return

    if bus["seats"] <= 0:
        print("Sorry, this bus is full.")
        return

    bus["seats"] -= 1
    bookings.append({
        "student_name": student_name,
        "student_id": student_id,
        "bus_number": bus["number"],
        "route": bus["route"],
    })

    print("\nBooking Confirmed!")
    print(f"Name: {student_name} ({student_id})")
    print(f"Bus:  {bus['number']} - {bus['route']}")
    print(f"Remaining seats on {bus['number']}: {bus['seats']}")


def view_my_bookings(student_id):
    print("\n--- MY BOOKINGS ---")
    my_list = [b for b in bookings if b["student_id"] == student_id]

    if not my_list:
        print("No active bookings found for your ID.")
        return

    for b in my_list:
        print(f"- Bus {b['bus_number']} ({b['route']})")


def cancel_booking(student_id):
    print("\n--- CANCEL BOOKING ---")
    bus_num = input("Enter bus number to cancel: ").upper()

    for booking in bookings:
        if booking["student_id"] == student_id and booking["bus_number"] == bus_num:
            bus = get_bus(bus_num)
            if bus:
                bus["seats"] += 1

            bookings.remove(booking)
            print(f"Successfully cancelled booking for bus {bus_num}.")
            return

    print(f"No booking found for bus {bus_num} under your ID.")


def bus_status():
    print("\n--- BUS STATUS ---")
    bus_num = input("Enter bus number: ")
    bus = get_bus(bus_num)

    if not bus:
        print("Bus not found.")
        return

    print(f"Bus {bus['number']} ({bus['route']}): {bus['status']}")


def summary_report():
    print("\n=== SYSTEM SUMMARY REPORT ===")
    total_capacity = sum(b["capacity"] for b in buses)
    total_available = sum(b["seats"] for b in buses)
    on_time_cnt = sum(1 for b in buses if b["status"] == "On Time")
    delayed_cnt = sum(1 for b in buses if b["status"] == "Delayed")

    print(f"Total Buses tracked: {len(buses)}")
    print(f"Total Capacity:      {total_capacity}")
    print(f"Seats Available:     {total_available}")
    print(f"Seats Booked:        {total_capacity - total_available}")
    print(f"Total Active Tickets:{len(bookings)}")
    print(f"Buses On Time:       {on_time_cnt}")
    print(f"Buses Delayed:       {delayed_cnt}")


def main():
    print("========================================")
    print("      COLLEGE TRANSPORT TRACKER")
    print("========================================")

    student_name = input("Enter your name: ")
    while student_name == "":
        student_name = input("Name cannot be empty. Try again: ")

    student_id = input("Enter your Student ID: ")
    while student_id == "":
        student_id = input("Student ID cannot be empty. Try again: ")

    while True:
        print("\n----------------------------------------")
        print("MENU")
        print("1. Search Bus")
        print("2. View Route & Stops")
        print("3. Check Seat Availability")
        print("4. Book Seat")
        print("5. View My Bookings")
        print("6. Cancel Booking")
        print("7. Check Bus Status")
        print("8. System Summary Report")
        print("9. Exit")
        print("----------------------------------------")

        try:
            choice = int(input("Select an option (1-9): "))
        except ValueError:
            print("Invalid input. Please enter a number.")
            continue

        if choice == 1:
            search_bus()
        elif choice == 2:
            view_route()
        elif choice == 3:
            check_seats()
        elif choice == 4:
            book_seat(student_name, student_id)
        elif choice == 5:
            view_my_bookings(student_id)
        elif choice == 6:
            cancel_booking(student_id)
        elif choice == 7:
            bus_status()
        elif choice == 8:
            summary_report()
        elif choice == 9:
            print(f"\nGoodbye {student_name}!")
            break
        else:
            print("Please pick a number between 1 and 9.")


if __name__ == "__main__":
    main()